version: "3.9"

services:
  api_backend:
    container_name: api_container
    image: api_backend
    depends_on:
      - db_postgres
      - pgadmin
    ports:
      - "3333:3333"

  db_postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_api_backend
    ports:
    - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - network-postgres-pgadim

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db_postgres
    networks:
      - network-postgres-pgadim

networks: 
  network-postgres-pgadim:
    driver: bridge



