version: "3.9"

services:
  api_backend:
    image: api_backend
    depends_on:
      - db_postgres
    ports:
      - "3333:3333"

  db_postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_api_backend
    ports:
    - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - network-postgres-pgadim

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "renatogroff@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - db_postgres
    networks:
      - network-postgres-pgadim

networks: 
  network-postgres-pgadim:
    driver: bridge



