version: "3.9"

services:
  db_postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_api_backend
    ports:
    - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api_backend:
    image:
    depends_on:
      - db_postgres
    ports:
      - "3333:3333"

